DROP DATABASE IF EXISTS springguru;
DROP USER IF EXISTS `springframework`@`%`;
CREATE DATABASE IF NOT EXISTS springguru CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `springframework`@`%` IDENTIFIED WITH mysql_native_password BY 'guru';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `springguru`.* TO `springframework`@`%`;
FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS qa2;
DROP USER IF EXISTS `springframeworkqa2`@`%`;
CREATE DATABASE IF NOT EXISTS qa2 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `springframeworkqa2`@`%` IDENTIFIED WITH mysql_native_password BY 'guru';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `qa2`.* TO `springframeworkqa2`@`%`;
FLUSH PRIVILEGES;